---
- hosts: node1
  become: yes
  tasks:
    - include_tasks: create-file.yml
    - name: install apache2 webserver
      apt:
       name: apache2
       state: present
    - name: Create a folder
      file:
       path: /home/maha/devops-labs
       state: directory
    - name: Copy a static file to remote machine
      copy:
       src: files/devops-info.txt
       dest: /home/maha/devops-labs/devops-info.txt
    - name: Create and copy a dynamic file using template module to remote modules
      template:
       src: templates/devops-info.j2
       dest: /var/www/html/index.html

