---
- hosts: webservers
  become: yes
  gather_facts: yes

  tasks:
   - name: Update apt-cache
     ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 3600
     when: ansible_os_family == "Debian"

   - name: Install Java on Debian
     ansible.builtin.apt:
      name: "{{ javaondebian }}"
      state: present  
     when: ansible_os_family == "Debian"

   - name: Update dnf-cache
     ansible.builtin.dnf:
        update_cache: yes
     when: ansible_os_family == "RedHat"

   - name: Install Java on RedHat
     ansible.builtin.dnf:
      name: "{{ javaonredhat }}"
      state: present
     when: ansible_os_family == "RedHat"

  