#SPDX-License-Identifier: MIT-0
---
# tasks file for tomcatrole
- include_tasks: installjava.yml
- include_tasks: downloadtomcat.yml
- include_tasks: usergroup.yml
- include_tasks: setpermissions.yml
- include_tasks: tomcatservice.yml
- include_tasks: starttomcat.yml
