---
- name: Change ownership of tomcat directory with -r
  ansible.builtin.file:
    path: /opt/tomcat/apache-tomcat-10.1.59
    owner: tomcat
    group: tomcat
    state: directory
    recurse: yes

- name: Set permissions chmod +x  on bin directory
  ansible.builtin.file: 
    path: /opt/tomcat/apache-tomcat-10.1.59/bin
    mode: '+x'
    recurse: yes
    state: directory