#SPDX-License-Identifier: MIT-0
---
# tasks file for mywebrole
- name: Install Web Server
  apt:
    name: "{{ webserver_package }}"
    state: present
- name: Copy a file
  copy:
    src: templates/file.txt
    dest: /var/www/html/index.html
  
